package com.erp.db.model;

import java.util.ArrayList;
import java.util.List;

public class ChargesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public ChargesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNull() {
            addCriterion("orderItemId is null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIsNotNull() {
            addCriterion("orderItemId is not null");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdEqualTo(Integer value) {
            addCriterion("orderItemId =", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotEqualTo(Integer value) {
            addCriterion("orderItemId <>", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThan(Integer value) {
            addCriterion("orderItemId >", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("orderItemId >=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThan(Integer value) {
            addCriterion("orderItemId <", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("orderItemId <=", value, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdIn(List<Integer> values) {
            addCriterion("orderItemId in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotIn(List<Integer> values) {
            addCriterion("orderItemId not in", values, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdBetween(Integer value1, Integer value2) {
            addCriterion("orderItemId between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andOrderItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("orderItemId not between", value1, value2, "orderItemId");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIsNull() {
            addCriterion("chargeType is null");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIsNotNull() {
            addCriterion("chargeType is not null");
            return (Criteria) this;
        }

        public Criteria andChargeTypeEqualTo(String value) {
            addCriterion("chargeType =", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotEqualTo(String value) {
            addCriterion("chargeType <>", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeGreaterThan(String value) {
            addCriterion("chargeType >", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("chargeType >=", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeLessThan(String value) {
            addCriterion("chargeType <", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeLessThanOrEqualTo(String value) {
            addCriterion("chargeType <=", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeLike(String value) {
            addCriterion("chargeType like", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotLike(String value) {
            addCriterion("chargeType not like", value, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeIn(List<String> values) {
            addCriterion("chargeType in", values, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotIn(List<String> values) {
            addCriterion("chargeType not in", values, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeBetween(String value1, String value2) {
            addCriterion("chargeType between", value1, value2, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeTypeNotBetween(String value1, String value2) {
            addCriterion("chargeType not between", value1, value2, "chargeType");
            return (Criteria) this;
        }

        public Criteria andChargeNameIsNull() {
            addCriterion("chargeName is null");
            return (Criteria) this;
        }

        public Criteria andChargeNameIsNotNull() {
            addCriterion("chargeName is not null");
            return (Criteria) this;
        }

        public Criteria andChargeNameEqualTo(String value) {
            addCriterion("chargeName =", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameNotEqualTo(String value) {
            addCriterion("chargeName <>", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameGreaterThan(String value) {
            addCriterion("chargeName >", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameGreaterThanOrEqualTo(String value) {
            addCriterion("chargeName >=", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameLessThan(String value) {
            addCriterion("chargeName <", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameLessThanOrEqualTo(String value) {
            addCriterion("chargeName <=", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameLike(String value) {
            addCriterion("chargeName like", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameNotLike(String value) {
            addCriterion("chargeName not like", value, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameIn(List<String> values) {
            addCriterion("chargeName in", values, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameNotIn(List<String> values) {
            addCriterion("chargeName not in", values, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameBetween(String value1, String value2) {
            addCriterion("chargeName between", value1, value2, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeNameNotBetween(String value1, String value2) {
            addCriterion("chargeName not between", value1, value2, "chargeName");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIsNull() {
            addCriterion("chargeAmount is null");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIsNotNull() {
            addCriterion("chargeAmount is not null");
            return (Criteria) this;
        }

        public Criteria andChargeAmountEqualTo(Double value) {
            addCriterion("chargeAmount =", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotEqualTo(Double value) {
            addCriterion("chargeAmount <>", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountGreaterThan(Double value) {
            addCriterion("chargeAmount >", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("chargeAmount >=", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountLessThan(Double value) {
            addCriterion("chargeAmount <", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountLessThanOrEqualTo(Double value) {
            addCriterion("chargeAmount <=", value, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountIn(List<Double> values) {
            addCriterion("chargeAmount in", values, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotIn(List<Double> values) {
            addCriterion("chargeAmount not in", values, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountBetween(Double value1, Double value2) {
            addCriterion("chargeAmount between", value1, value2, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeAmountNotBetween(Double value1, Double value2) {
            addCriterion("chargeAmount not between", value1, value2, "chargeAmount");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyIsNull() {
            addCriterion("chargeCurrency is null");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyIsNotNull() {
            addCriterion("chargeCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyEqualTo(String value) {
            addCriterion("chargeCurrency =", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyNotEqualTo(String value) {
            addCriterion("chargeCurrency <>", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyGreaterThan(String value) {
            addCriterion("chargeCurrency >", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("chargeCurrency >=", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyLessThan(String value) {
            addCriterion("chargeCurrency <", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyLessThanOrEqualTo(String value) {
            addCriterion("chargeCurrency <=", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyLike(String value) {
            addCriterion("chargeCurrency like", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyNotLike(String value) {
            addCriterion("chargeCurrency not like", value, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyIn(List<String> values) {
            addCriterion("chargeCurrency in", values, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyNotIn(List<String> values) {
            addCriterion("chargeCurrency not in", values, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyBetween(String value1, String value2) {
            addCriterion("chargeCurrency between", value1, value2, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andChargeCurrencyNotBetween(String value1, String value2) {
            addCriterion("chargeCurrency not between", value1, value2, "chargeCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxNameIsNull() {
            addCriterion("taxName is null");
            return (Criteria) this;
        }

        public Criteria andTaxNameIsNotNull() {
            addCriterion("taxName is not null");
            return (Criteria) this;
        }

        public Criteria andTaxNameEqualTo(String value) {
            addCriterion("taxName =", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameNotEqualTo(String value) {
            addCriterion("taxName <>", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameGreaterThan(String value) {
            addCriterion("taxName >", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameGreaterThanOrEqualTo(String value) {
            addCriterion("taxName >=", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameLessThan(String value) {
            addCriterion("taxName <", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameLessThanOrEqualTo(String value) {
            addCriterion("taxName <=", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameLike(String value) {
            addCriterion("taxName like", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameNotLike(String value) {
            addCriterion("taxName not like", value, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameIn(List<String> values) {
            addCriterion("taxName in", values, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameNotIn(List<String> values) {
            addCriterion("taxName not in", values, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameBetween(String value1, String value2) {
            addCriterion("taxName between", value1, value2, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxNameNotBetween(String value1, String value2) {
            addCriterion("taxName not between", value1, value2, "taxName");
            return (Criteria) this;
        }

        public Criteria andTaxAmountIsNull() {
            addCriterion("taxAmount is null");
            return (Criteria) this;
        }

        public Criteria andTaxAmountIsNotNull() {
            addCriterion("taxAmount is not null");
            return (Criteria) this;
        }

        public Criteria andTaxAmountEqualTo(Double value) {
            addCriterion("taxAmount =", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountNotEqualTo(Double value) {
            addCriterion("taxAmount <>", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountGreaterThan(Double value) {
            addCriterion("taxAmount >", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountGreaterThanOrEqualTo(Double value) {
            addCriterion("taxAmount >=", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountLessThan(Double value) {
            addCriterion("taxAmount <", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountLessThanOrEqualTo(Double value) {
            addCriterion("taxAmount <=", value, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountIn(List<Double> values) {
            addCriterion("taxAmount in", values, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountNotIn(List<Double> values) {
            addCriterion("taxAmount not in", values, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountBetween(Double value1, Double value2) {
            addCriterion("taxAmount between", value1, value2, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxAmountNotBetween(Double value1, Double value2) {
            addCriterion("taxAmount not between", value1, value2, "taxAmount");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyIsNull() {
            addCriterion("taxCurrency is null");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyIsNotNull() {
            addCriterion("taxCurrency is not null");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyEqualTo(String value) {
            addCriterion("taxCurrency =", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyNotEqualTo(String value) {
            addCriterion("taxCurrency <>", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyGreaterThan(String value) {
            addCriterion("taxCurrency >", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("taxCurrency >=", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyLessThan(String value) {
            addCriterion("taxCurrency <", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyLessThanOrEqualTo(String value) {
            addCriterion("taxCurrency <=", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyLike(String value) {
            addCriterion("taxCurrency like", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyNotLike(String value) {
            addCriterion("taxCurrency not like", value, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyIn(List<String> values) {
            addCriterion("taxCurrency in", values, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyNotIn(List<String> values) {
            addCriterion("taxCurrency not in", values, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyBetween(String value1, String value2) {
            addCriterion("taxCurrency between", value1, value2, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andTaxCurrencyNotBetween(String value1, String value2) {
            addCriterion("taxCurrency not between", value1, value2, "taxCurrency");
            return (Criteria) this;
        }

        public Criteria andRefundReasonIsNull() {
            addCriterion("refundReason is null");
            return (Criteria) this;
        }

        public Criteria andRefundReasonIsNotNull() {
            addCriterion("refundReason is not null");
            return (Criteria) this;
        }

        public Criteria andRefundReasonEqualTo(String value) {
            addCriterion("refundReason =", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonNotEqualTo(String value) {
            addCriterion("refundReason <>", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonGreaterThan(String value) {
            addCriterion("refundReason >", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonGreaterThanOrEqualTo(String value) {
            addCriterion("refundReason >=", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonLessThan(String value) {
            addCriterion("refundReason <", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonLessThanOrEqualTo(String value) {
            addCriterion("refundReason <=", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonLike(String value) {
            addCriterion("refundReason like", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonNotLike(String value) {
            addCriterion("refundReason not like", value, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonIn(List<String> values) {
            addCriterion("refundReason in", values, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonNotIn(List<String> values) {
            addCriterion("refundReason not in", values, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonBetween(String value1, String value2) {
            addCriterion("refundReason between", value1, value2, "refundReason");
            return (Criteria) this;
        }

        public Criteria andRefundReasonNotBetween(String value1, String value2) {
            addCriterion("refundReason not between", value1, value2, "refundReason");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryIsNull() {
            addCriterion("chargeCategory is null");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryIsNotNull() {
            addCriterion("chargeCategory is not null");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryEqualTo(String value) {
            addCriterion("chargeCategory =", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryNotEqualTo(String value) {
            addCriterion("chargeCategory <>", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryGreaterThan(String value) {
            addCriterion("chargeCategory >", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("chargeCategory >=", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryLessThan(String value) {
            addCriterion("chargeCategory <", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryLessThanOrEqualTo(String value) {
            addCriterion("chargeCategory <=", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryLike(String value) {
            addCriterion("chargeCategory like", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryNotLike(String value) {
            addCriterion("chargeCategory not like", value, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryIn(List<String> values) {
            addCriterion("chargeCategory in", values, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryNotIn(List<String> values) {
            addCriterion("chargeCategory not in", values, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryBetween(String value1, String value2) {
            addCriterion("chargeCategory between", value1, value2, "chargeCategory");
            return (Criteria) this;
        }

        public Criteria andChargeCategoryNotBetween(String value1, String value2) {
            addCriterion("chargeCategory not between", value1, value2, "chargeCategory");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charges
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 11 11:08:57 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}