package com.erp.db.model;

import java.util.Date;

public class Feed {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.id
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.userId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.feedId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private String feedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.feedType
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private String feedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemsReceived
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemsReceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemsSucceeded
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemsSucceeded;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemsFailed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemsFailed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemsProcessing
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemsProcessing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.feedStatus
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private String feedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.feedDate
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Date feedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.modifiedDtm
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Date modifiedDtm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemDataErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemDataErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemSystemErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemSystemErrorCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.itemTimeoutErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    private Integer itemTimeoutErrorCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.id
     *
     * @return the value of feed.id
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.id
     *
     * @param id the value for feed.id
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.userId
     *
     * @return the value of feed.userId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.userId
     *
     * @param userId the value for feed.userId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.feedId
     *
     * @return the value of feed.feedId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public String getFeedId() {
        return feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.feedId
     *
     * @param feedId the value for feed.feedId
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setFeedId(String feedId) {
        this.feedId = feedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.feedType
     *
     * @return the value of feed.feedType
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public String getFeedType() {
        return feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.feedType
     *
     * @param feedType the value for feed.feedType
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setFeedType(String feedType) {
        this.feedType = feedType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemsReceived
     *
     * @return the value of feed.itemsReceived
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemsReceived() {
        return itemsReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemsReceived
     *
     * @param itemsReceived the value for feed.itemsReceived
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemsReceived(Integer itemsReceived) {
        this.itemsReceived = itemsReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemsSucceeded
     *
     * @return the value of feed.itemsSucceeded
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemsSucceeded() {
        return itemsSucceeded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemsSucceeded
     *
     * @param itemsSucceeded the value for feed.itemsSucceeded
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemsSucceeded(Integer itemsSucceeded) {
        this.itemsSucceeded = itemsSucceeded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemsFailed
     *
     * @return the value of feed.itemsFailed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemsFailed() {
        return itemsFailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemsFailed
     *
     * @param itemsFailed the value for feed.itemsFailed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemsFailed(Integer itemsFailed) {
        this.itemsFailed = itemsFailed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemsProcessing
     *
     * @return the value of feed.itemsProcessing
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemsProcessing() {
        return itemsProcessing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemsProcessing
     *
     * @param itemsProcessing the value for feed.itemsProcessing
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemsProcessing(Integer itemsProcessing) {
        this.itemsProcessing = itemsProcessing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.feedStatus
     *
     * @return the value of feed.feedStatus
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public String getFeedStatus() {
        return feedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.feedStatus
     *
     * @param feedStatus the value for feed.feedStatus
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setFeedStatus(String feedStatus) {
        this.feedStatus = feedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.feedDate
     *
     * @return the value of feed.feedDate
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Date getFeedDate() {
        return feedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.feedDate
     *
     * @param feedDate the value for feed.feedDate
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setFeedDate(Date feedDate) {
        this.feedDate = feedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.modifiedDtm
     *
     * @return the value of feed.modifiedDtm
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Date getModifiedDtm() {
        return modifiedDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.modifiedDtm
     *
     * @param modifiedDtm the value for feed.modifiedDtm
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setModifiedDtm(Date modifiedDtm) {
        this.modifiedDtm = modifiedDtm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemDataErrorCount
     *
     * @return the value of feed.itemDataErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemDataErrorCount() {
        return itemDataErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemDataErrorCount
     *
     * @param itemDataErrorCount the value for feed.itemDataErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemDataErrorCount(Integer itemDataErrorCount) {
        this.itemDataErrorCount = itemDataErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemSystemErrorCount
     *
     * @return the value of feed.itemSystemErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemSystemErrorCount() {
        return itemSystemErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemSystemErrorCount
     *
     * @param itemSystemErrorCount the value for feed.itemSystemErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemSystemErrorCount(Integer itemSystemErrorCount) {
        this.itemSystemErrorCount = itemSystemErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.itemTimeoutErrorCount
     *
     * @return the value of feed.itemTimeoutErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Integer getItemTimeoutErrorCount() {
        return itemTimeoutErrorCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.itemTimeoutErrorCount
     *
     * @param itemTimeoutErrorCount the value for feed.itemTimeoutErrorCount
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setItemTimeoutErrorCount(Integer itemTimeoutErrorCount) {
        this.itemTimeoutErrorCount = itemTimeoutErrorCount;
    }
}