package com.erp.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class FeedExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public FeedExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFeedIdIsNull() {
            addCriterion("feedId is null");
            return (Criteria) this;
        }

        public Criteria andFeedIdIsNotNull() {
            addCriterion("feedId is not null");
            return (Criteria) this;
        }

        public Criteria andFeedIdEqualTo(String value) {
            addCriterion("feedId =", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdNotEqualTo(String value) {
            addCriterion("feedId <>", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdGreaterThan(String value) {
            addCriterion("feedId >", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdGreaterThanOrEqualTo(String value) {
            addCriterion("feedId >=", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdLessThan(String value) {
            addCriterion("feedId <", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdLessThanOrEqualTo(String value) {
            addCriterion("feedId <=", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdLike(String value) {
            addCriterion("feedId like", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdNotLike(String value) {
            addCriterion("feedId not like", value, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdIn(List<String> values) {
            addCriterion("feedId in", values, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdNotIn(List<String> values) {
            addCriterion("feedId not in", values, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdBetween(String value1, String value2) {
            addCriterion("feedId between", value1, value2, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedIdNotBetween(String value1, String value2) {
            addCriterion("feedId not between", value1, value2, "feedId");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIsNull() {
            addCriterion("feedType is null");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIsNotNull() {
            addCriterion("feedType is not null");
            return (Criteria) this;
        }

        public Criteria andFeedTypeEqualTo(String value) {
            addCriterion("feedType =", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotEqualTo(String value) {
            addCriterion("feedType <>", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeGreaterThan(String value) {
            addCriterion("feedType >", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeGreaterThanOrEqualTo(String value) {
            addCriterion("feedType >=", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLessThan(String value) {
            addCriterion("feedType <", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLessThanOrEqualTo(String value) {
            addCriterion("feedType <=", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeLike(String value) {
            addCriterion("feedType like", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotLike(String value) {
            addCriterion("feedType not like", value, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeIn(List<String> values) {
            addCriterion("feedType in", values, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotIn(List<String> values) {
            addCriterion("feedType not in", values, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeBetween(String value1, String value2) {
            addCriterion("feedType between", value1, value2, "feedType");
            return (Criteria) this;
        }

        public Criteria andFeedTypeNotBetween(String value1, String value2) {
            addCriterion("feedType not between", value1, value2, "feedType");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedIsNull() {
            addCriterion("itemsReceived is null");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedIsNotNull() {
            addCriterion("itemsReceived is not null");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedEqualTo(Integer value) {
            addCriterion("itemsReceived =", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedNotEqualTo(Integer value) {
            addCriterion("itemsReceived <>", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedGreaterThan(Integer value) {
            addCriterion("itemsReceived >", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemsReceived >=", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedLessThan(Integer value) {
            addCriterion("itemsReceived <", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedLessThanOrEqualTo(Integer value) {
            addCriterion("itemsReceived <=", value, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedIn(List<Integer> values) {
            addCriterion("itemsReceived in", values, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedNotIn(List<Integer> values) {
            addCriterion("itemsReceived not in", values, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedBetween(Integer value1, Integer value2) {
            addCriterion("itemsReceived between", value1, value2, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsReceivedNotBetween(Integer value1, Integer value2) {
            addCriterion("itemsReceived not between", value1, value2, "itemsReceived");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededIsNull() {
            addCriterion("itemsSucceeded is null");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededIsNotNull() {
            addCriterion("itemsSucceeded is not null");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededEqualTo(Integer value) {
            addCriterion("itemsSucceeded =", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededNotEqualTo(Integer value) {
            addCriterion("itemsSucceeded <>", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededGreaterThan(Integer value) {
            addCriterion("itemsSucceeded >", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemsSucceeded >=", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededLessThan(Integer value) {
            addCriterion("itemsSucceeded <", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededLessThanOrEqualTo(Integer value) {
            addCriterion("itemsSucceeded <=", value, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededIn(List<Integer> values) {
            addCriterion("itemsSucceeded in", values, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededNotIn(List<Integer> values) {
            addCriterion("itemsSucceeded not in", values, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededBetween(Integer value1, Integer value2) {
            addCriterion("itemsSucceeded between", value1, value2, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsSucceededNotBetween(Integer value1, Integer value2) {
            addCriterion("itemsSucceeded not between", value1, value2, "itemsSucceeded");
            return (Criteria) this;
        }

        public Criteria andItemsFailedIsNull() {
            addCriterion("itemsFailed is null");
            return (Criteria) this;
        }

        public Criteria andItemsFailedIsNotNull() {
            addCriterion("itemsFailed is not null");
            return (Criteria) this;
        }

        public Criteria andItemsFailedEqualTo(Integer value) {
            addCriterion("itemsFailed =", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedNotEqualTo(Integer value) {
            addCriterion("itemsFailed <>", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedGreaterThan(Integer value) {
            addCriterion("itemsFailed >", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemsFailed >=", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedLessThan(Integer value) {
            addCriterion("itemsFailed <", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedLessThanOrEqualTo(Integer value) {
            addCriterion("itemsFailed <=", value, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedIn(List<Integer> values) {
            addCriterion("itemsFailed in", values, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedNotIn(List<Integer> values) {
            addCriterion("itemsFailed not in", values, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedBetween(Integer value1, Integer value2) {
            addCriterion("itemsFailed between", value1, value2, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsFailedNotBetween(Integer value1, Integer value2) {
            addCriterion("itemsFailed not between", value1, value2, "itemsFailed");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingIsNull() {
            addCriterion("itemsProcessing is null");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingIsNotNull() {
            addCriterion("itemsProcessing is not null");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingEqualTo(Integer value) {
            addCriterion("itemsProcessing =", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingNotEqualTo(Integer value) {
            addCriterion("itemsProcessing <>", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingGreaterThan(Integer value) {
            addCriterion("itemsProcessing >", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemsProcessing >=", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingLessThan(Integer value) {
            addCriterion("itemsProcessing <", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingLessThanOrEqualTo(Integer value) {
            addCriterion("itemsProcessing <=", value, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingIn(List<Integer> values) {
            addCriterion("itemsProcessing in", values, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingNotIn(List<Integer> values) {
            addCriterion("itemsProcessing not in", values, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingBetween(Integer value1, Integer value2) {
            addCriterion("itemsProcessing between", value1, value2, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andItemsProcessingNotBetween(Integer value1, Integer value2) {
            addCriterion("itemsProcessing not between", value1, value2, "itemsProcessing");
            return (Criteria) this;
        }

        public Criteria andFeedStatusIsNull() {
            addCriterion("feedStatus is null");
            return (Criteria) this;
        }

        public Criteria andFeedStatusIsNotNull() {
            addCriterion("feedStatus is not null");
            return (Criteria) this;
        }

        public Criteria andFeedStatusEqualTo(String value) {
            addCriterion("feedStatus =", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusNotEqualTo(String value) {
            addCriterion("feedStatus <>", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusGreaterThan(String value) {
            addCriterion("feedStatus >", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusGreaterThanOrEqualTo(String value) {
            addCriterion("feedStatus >=", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusLessThan(String value) {
            addCriterion("feedStatus <", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusLessThanOrEqualTo(String value) {
            addCriterion("feedStatus <=", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusLike(String value) {
            addCriterion("feedStatus like", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusNotLike(String value) {
            addCriterion("feedStatus not like", value, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusIn(List<String> values) {
            addCriterion("feedStatus in", values, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusNotIn(List<String> values) {
            addCriterion("feedStatus not in", values, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusBetween(String value1, String value2) {
            addCriterion("feedStatus between", value1, value2, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedStatusNotBetween(String value1, String value2) {
            addCriterion("feedStatus not between", value1, value2, "feedStatus");
            return (Criteria) this;
        }

        public Criteria andFeedDateIsNull() {
            addCriterion("feedDate is null");
            return (Criteria) this;
        }

        public Criteria andFeedDateIsNotNull() {
            addCriterion("feedDate is not null");
            return (Criteria) this;
        }

        public Criteria andFeedDateEqualTo(Date value) {
            addCriterion("feedDate =", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateNotEqualTo(Date value) {
            addCriterion("feedDate <>", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateGreaterThan(Date value) {
            addCriterion("feedDate >", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("feedDate >=", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateLessThan(Date value) {
            addCriterion("feedDate <", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateLessThanOrEqualTo(Date value) {
            addCriterion("feedDate <=", value, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateIn(List<Date> values) {
            addCriterion("feedDate in", values, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateNotIn(List<Date> values) {
            addCriterion("feedDate not in", values, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateBetween(Date value1, Date value2) {
            addCriterion("feedDate between", value1, value2, "feedDate");
            return (Criteria) this;
        }

        public Criteria andFeedDateNotBetween(Date value1, Date value2) {
            addCriterion("feedDate not between", value1, value2, "feedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmIsNull() {
            addCriterion("modifiedDtm is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmIsNotNull() {
            addCriterion("modifiedDtm is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmEqualTo(Date value) {
            addCriterion("modifiedDtm =", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmNotEqualTo(Date value) {
            addCriterion("modifiedDtm <>", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmGreaterThan(Date value) {
            addCriterion("modifiedDtm >", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmGreaterThanOrEqualTo(Date value) {
            addCriterion("modifiedDtm >=", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmLessThan(Date value) {
            addCriterion("modifiedDtm <", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmLessThanOrEqualTo(Date value) {
            addCriterion("modifiedDtm <=", value, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmIn(List<Date> values) {
            addCriterion("modifiedDtm in", values, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmNotIn(List<Date> values) {
            addCriterion("modifiedDtm not in", values, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmBetween(Date value1, Date value2) {
            addCriterion("modifiedDtm between", value1, value2, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andModifiedDtmNotBetween(Date value1, Date value2) {
            addCriterion("modifiedDtm not between", value1, value2, "modifiedDtm");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountIsNull() {
            addCriterion("itemDataErrorCount is null");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountIsNotNull() {
            addCriterion("itemDataErrorCount is not null");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountEqualTo(Integer value) {
            addCriterion("itemDataErrorCount =", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountNotEqualTo(Integer value) {
            addCriterion("itemDataErrorCount <>", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountGreaterThan(Integer value) {
            addCriterion("itemDataErrorCount >", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemDataErrorCount >=", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountLessThan(Integer value) {
            addCriterion("itemDataErrorCount <", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountLessThanOrEqualTo(Integer value) {
            addCriterion("itemDataErrorCount <=", value, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountIn(List<Integer> values) {
            addCriterion("itemDataErrorCount in", values, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountNotIn(List<Integer> values) {
            addCriterion("itemDataErrorCount not in", values, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountBetween(Integer value1, Integer value2) {
            addCriterion("itemDataErrorCount between", value1, value2, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemDataErrorCountNotBetween(Integer value1, Integer value2) {
            addCriterion("itemDataErrorCount not between", value1, value2, "itemDataErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountIsNull() {
            addCriterion("itemSystemErrorCount is null");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountIsNotNull() {
            addCriterion("itemSystemErrorCount is not null");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountEqualTo(Integer value) {
            addCriterion("itemSystemErrorCount =", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountNotEqualTo(Integer value) {
            addCriterion("itemSystemErrorCount <>", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountGreaterThan(Integer value) {
            addCriterion("itemSystemErrorCount >", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemSystemErrorCount >=", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountLessThan(Integer value) {
            addCriterion("itemSystemErrorCount <", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountLessThanOrEqualTo(Integer value) {
            addCriterion("itemSystemErrorCount <=", value, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountIn(List<Integer> values) {
            addCriterion("itemSystemErrorCount in", values, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountNotIn(List<Integer> values) {
            addCriterion("itemSystemErrorCount not in", values, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountBetween(Integer value1, Integer value2) {
            addCriterion("itemSystemErrorCount between", value1, value2, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemSystemErrorCountNotBetween(Integer value1, Integer value2) {
            addCriterion("itemSystemErrorCount not between", value1, value2, "itemSystemErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountIsNull() {
            addCriterion("itemTimeoutErrorCount is null");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountIsNotNull() {
            addCriterion("itemTimeoutErrorCount is not null");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountEqualTo(Integer value) {
            addCriterion("itemTimeoutErrorCount =", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountNotEqualTo(Integer value) {
            addCriterion("itemTimeoutErrorCount <>", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountGreaterThan(Integer value) {
            addCriterion("itemTimeoutErrorCount >", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("itemTimeoutErrorCount >=", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountLessThan(Integer value) {
            addCriterion("itemTimeoutErrorCount <", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountLessThanOrEqualTo(Integer value) {
            addCriterion("itemTimeoutErrorCount <=", value, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountIn(List<Integer> values) {
            addCriterion("itemTimeoutErrorCount in", values, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountNotIn(List<Integer> values) {
            addCriterion("itemTimeoutErrorCount not in", values, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountBetween(Integer value1, Integer value2) {
            addCriterion("itemTimeoutErrorCount between", value1, value2, "itemTimeoutErrorCount");
            return (Criteria) this;
        }

        public Criteria andItemTimeoutErrorCountNotBetween(Integer value1, Integer value2) {
            addCriterion("itemTimeoutErrorCount not between", value1, value2, "itemTimeoutErrorCount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feed
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 05 15:23:18 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}