package com.erp.db.model;

import java.util.ArrayList;
import java.util.List;

public class ItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public ItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andMartIsNull() {
            addCriterion("mart is null");
            return (Criteria) this;
        }

        public Criteria andMartIsNotNull() {
            addCriterion("mart is not null");
            return (Criteria) this;
        }

        public Criteria andMartEqualTo(String value) {
            addCriterion("mart =", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartNotEqualTo(String value) {
            addCriterion("mart <>", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartGreaterThan(String value) {
            addCriterion("mart >", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartGreaterThanOrEqualTo(String value) {
            addCriterion("mart >=", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartLessThan(String value) {
            addCriterion("mart <", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartLessThanOrEqualTo(String value) {
            addCriterion("mart <=", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartLike(String value) {
            addCriterion("mart like", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartNotLike(String value) {
            addCriterion("mart not like", value, "mart");
            return (Criteria) this;
        }

        public Criteria andMartIn(List<String> values) {
            addCriterion("mart in", values, "mart");
            return (Criteria) this;
        }

        public Criteria andMartNotIn(List<String> values) {
            addCriterion("mart not in", values, "mart");
            return (Criteria) this;
        }

        public Criteria andMartBetween(String value1, String value2) {
            addCriterion("mart between", value1, value2, "mart");
            return (Criteria) this;
        }

        public Criteria andMartNotBetween(String value1, String value2) {
            addCriterion("mart not between", value1, value2, "mart");
            return (Criteria) this;
        }

        public Criteria andSkuIsNull() {
            addCriterion("sku is null");
            return (Criteria) this;
        }

        public Criteria andSkuIsNotNull() {
            addCriterion("sku is not null");
            return (Criteria) this;
        }

        public Criteria andSkuEqualTo(String value) {
            addCriterion("sku =", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotEqualTo(String value) {
            addCriterion("sku <>", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThan(String value) {
            addCriterion("sku >", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuGreaterThanOrEqualTo(String value) {
            addCriterion("sku >=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThan(String value) {
            addCriterion("sku <", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLessThanOrEqualTo(String value) {
            addCriterion("sku <=", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuLike(String value) {
            addCriterion("sku like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotLike(String value) {
            addCriterion("sku not like", value, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuIn(List<String> values) {
            addCriterion("sku in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotIn(List<String> values) {
            addCriterion("sku not in", values, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuBetween(String value1, String value2) {
            addCriterion("sku between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andSkuNotBetween(String value1, String value2) {
            addCriterion("sku not between", value1, value2, "sku");
            return (Criteria) this;
        }

        public Criteria andWpidIsNull() {
            addCriterion("wpid is null");
            return (Criteria) this;
        }

        public Criteria andWpidIsNotNull() {
            addCriterion("wpid is not null");
            return (Criteria) this;
        }

        public Criteria andWpidEqualTo(String value) {
            addCriterion("wpid =", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidNotEqualTo(String value) {
            addCriterion("wpid <>", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidGreaterThan(String value) {
            addCriterion("wpid >", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidGreaterThanOrEqualTo(String value) {
            addCriterion("wpid >=", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidLessThan(String value) {
            addCriterion("wpid <", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidLessThanOrEqualTo(String value) {
            addCriterion("wpid <=", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidLike(String value) {
            addCriterion("wpid like", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidNotLike(String value) {
            addCriterion("wpid not like", value, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidIn(List<String> values) {
            addCriterion("wpid in", values, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidNotIn(List<String> values) {
            addCriterion("wpid not in", values, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidBetween(String value1, String value2) {
            addCriterion("wpid between", value1, value2, "wpid");
            return (Criteria) this;
        }

        public Criteria andWpidNotBetween(String value1, String value2) {
            addCriterion("wpid not between", value1, value2, "wpid");
            return (Criteria) this;
        }

        public Criteria andUpcIsNull() {
            addCriterion("upc is null");
            return (Criteria) this;
        }

        public Criteria andUpcIsNotNull() {
            addCriterion("upc is not null");
            return (Criteria) this;
        }

        public Criteria andUpcEqualTo(String value) {
            addCriterion("upc =", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcNotEqualTo(String value) {
            addCriterion("upc <>", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcGreaterThan(String value) {
            addCriterion("upc >", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcGreaterThanOrEqualTo(String value) {
            addCriterion("upc >=", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcLessThan(String value) {
            addCriterion("upc <", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcLessThanOrEqualTo(String value) {
            addCriterion("upc <=", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcLike(String value) {
            addCriterion("upc like", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcNotLike(String value) {
            addCriterion("upc not like", value, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcIn(List<String> values) {
            addCriterion("upc in", values, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcNotIn(List<String> values) {
            addCriterion("upc not in", values, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcBetween(String value1, String value2) {
            addCriterion("upc between", value1, value2, "upc");
            return (Criteria) this;
        }

        public Criteria andUpcNotBetween(String value1, String value2) {
            addCriterion("upc not between", value1, value2, "upc");
            return (Criteria) this;
        }

        public Criteria andGtinIsNull() {
            addCriterion("gtin is null");
            return (Criteria) this;
        }

        public Criteria andGtinIsNotNull() {
            addCriterion("gtin is not null");
            return (Criteria) this;
        }

        public Criteria andGtinEqualTo(String value) {
            addCriterion("gtin =", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinNotEqualTo(String value) {
            addCriterion("gtin <>", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinGreaterThan(String value) {
            addCriterion("gtin >", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinGreaterThanOrEqualTo(String value) {
            addCriterion("gtin >=", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinLessThan(String value) {
            addCriterion("gtin <", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinLessThanOrEqualTo(String value) {
            addCriterion("gtin <=", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinLike(String value) {
            addCriterion("gtin like", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinNotLike(String value) {
            addCriterion("gtin not like", value, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinIn(List<String> values) {
            addCriterion("gtin in", values, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinNotIn(List<String> values) {
            addCriterion("gtin not in", values, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinBetween(String value1, String value2) {
            addCriterion("gtin between", value1, value2, "gtin");
            return (Criteria) this;
        }

        public Criteria andGtinNotBetween(String value1, String value2) {
            addCriterion("gtin not between", value1, value2, "gtin");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("productName is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("productName is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("productName =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("productName <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("productName >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("productName >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("productName <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("productName <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("productName like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("productName not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("productName in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("productName not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("productName between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("productName not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("productType is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("productType is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(String value) {
            addCriterion("productType =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(String value) {
            addCriterion("productType <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(String value) {
            addCriterion("productType >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(String value) {
            addCriterion("productType >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(String value) {
            addCriterion("productType <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(String value) {
            addCriterion("productType <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLike(String value) {
            addCriterion("productType like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotLike(String value) {
            addCriterion("productType not like", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<String> values) {
            addCriterion("productType in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<String> values) {
            addCriterion("productType not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(String value1, String value2) {
            addCriterion("productType between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(String value1, String value2) {
            addCriterion("productType not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("currency is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("currency is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("currency =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("currency <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("currency >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("currency >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("currency <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("currency <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("currency like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("currency not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("currency in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("currency not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("currency between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("currency not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andPrice_amountIsNull() {
            addCriterion("price_amount is null");
            return (Criteria) this;
        }

        public Criteria andPrice_amountIsNotNull() {
            addCriterion("price_amount is not null");
            return (Criteria) this;
        }

        public Criteria andPrice_amountEqualTo(Double value) {
            addCriterion("price_amount =", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountNotEqualTo(Double value) {
            addCriterion("price_amount <>", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountGreaterThan(Double value) {
            addCriterion("price_amount >", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountGreaterThanOrEqualTo(Double value) {
            addCriterion("price_amount >=", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountLessThan(Double value) {
            addCriterion("price_amount <", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountLessThanOrEqualTo(Double value) {
            addCriterion("price_amount <=", value, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountIn(List<Double> values) {
            addCriterion("price_amount in", values, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountNotIn(List<Double> values) {
            addCriterion("price_amount not in", values, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountBetween(Double value1, Double value2) {
            addCriterion("price_amount between", value1, value2, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPrice_amountNotBetween(Double value1, Double value2) {
            addCriterion("price_amount not between", value1, value2, "price_amount");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusIsNull() {
            addCriterion("publishedStatus is null");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusIsNotNull() {
            addCriterion("publishedStatus is not null");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusEqualTo(String value) {
            addCriterion("publishedStatus =", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusNotEqualTo(String value) {
            addCriterion("publishedStatus <>", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusGreaterThan(String value) {
            addCriterion("publishedStatus >", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusGreaterThanOrEqualTo(String value) {
            addCriterion("publishedStatus >=", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusLessThan(String value) {
            addCriterion("publishedStatus <", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusLessThanOrEqualTo(String value) {
            addCriterion("publishedStatus <=", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusLike(String value) {
            addCriterion("publishedStatus like", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusNotLike(String value) {
            addCriterion("publishedStatus not like", value, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusIn(List<String> values) {
            addCriterion("publishedStatus in", values, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusNotIn(List<String> values) {
            addCriterion("publishedStatus not in", values, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusBetween(String value1, String value2) {
            addCriterion("publishedStatus between", value1, value2, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andPublishedStatusNotBetween(String value1, String value2) {
            addCriterion("publishedStatus not between", value1, value2, "publishedStatus");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andInv_amountIsNull() {
            addCriterion("inv_amount is null");
            return (Criteria) this;
        }

        public Criteria andInv_amountIsNotNull() {
            addCriterion("inv_amount is not null");
            return (Criteria) this;
        }

        public Criteria andInv_amountEqualTo(Integer value) {
            addCriterion("inv_amount =", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountNotEqualTo(Integer value) {
            addCriterion("inv_amount <>", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountGreaterThan(Integer value) {
            addCriterion("inv_amount >", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountGreaterThanOrEqualTo(Integer value) {
            addCriterion("inv_amount >=", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountLessThan(Integer value) {
            addCriterion("inv_amount <", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountLessThanOrEqualTo(Integer value) {
            addCriterion("inv_amount <=", value, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountIn(List<Integer> values) {
            addCriterion("inv_amount in", values, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountNotIn(List<Integer> values) {
            addCriterion("inv_amount not in", values, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountBetween(Integer value1, Integer value2) {
            addCriterion("inv_amount between", value1, value2, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andInv_amountNotBetween(Integer value1, Integer value2) {
            addCriterion("inv_amount not between", value1, value2, "inv_amount");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeIsNull() {
            addCriterion("fulfillmentLagTime is null");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeIsNotNull() {
            addCriterion("fulfillmentLagTime is not null");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeEqualTo(Integer value) {
            addCriterion("fulfillmentLagTime =", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeNotEqualTo(Integer value) {
            addCriterion("fulfillmentLagTime <>", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeGreaterThan(Integer value) {
            addCriterion("fulfillmentLagTime >", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("fulfillmentLagTime >=", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeLessThan(Integer value) {
            addCriterion("fulfillmentLagTime <", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeLessThanOrEqualTo(Integer value) {
            addCriterion("fulfillmentLagTime <=", value, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeIn(List<Integer> values) {
            addCriterion("fulfillmentLagTime in", values, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeNotIn(List<Integer> values) {
            addCriterion("fulfillmentLagTime not in", values, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeBetween(Integer value1, Integer value2) {
            addCriterion("fulfillmentLagTime between", value1, value2, "fulfillmentLagTime");
            return (Criteria) this;
        }

        public Criteria andFulfillmentLagTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("fulfillmentLagTime not between", value1, value2, "fulfillmentLagTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 19 20:18:37 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table item
     *
     * @mbggenerated Mon Jun 19 20:18:37 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}