package com.erp.db.model;

import java.util.Date;

public class Orders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.userId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.purchaseOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private String purchaseOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customerOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private String customerOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customerEmailId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private String customerEmailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderDate
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderStatus
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    private String orderStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.userId
     *
     * @return the value of orders.userId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.userId
     *
     * @param userId the value for orders.userId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.purchaseOrderId
     *
     * @return the value of orders.purchaseOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public String getPurchaseOrderId() {
        return purchaseOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.purchaseOrderId
     *
     * @param purchaseOrderId the value for orders.purchaseOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setPurchaseOrderId(String purchaseOrderId) {
        this.purchaseOrderId = purchaseOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customerOrderId
     *
     * @return the value of orders.customerOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public String getCustomerOrderId() {
        return customerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customerOrderId
     *
     * @param customerOrderId the value for orders.customerOrderId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setCustomerOrderId(String customerOrderId) {
        this.customerOrderId = customerOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customerEmailId
     *
     * @return the value of orders.customerEmailId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public String getCustomerEmailId() {
        return customerEmailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customerEmailId
     *
     * @param customerEmailId the value for orders.customerEmailId
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setCustomerEmailId(String customerEmailId) {
        this.customerEmailId = customerEmailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderDate
     *
     * @return the value of orders.orderDate
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderDate
     *
     * @param orderDate the value for orders.orderDate
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderStatus
     *
     * @return the value of orders.orderStatus
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderStatus
     *
     * @param orderStatus the value for orders.orderStatus
     *
     * @mbggenerated Wed Jun 07 11:19:02 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }
}