package com.erp.db.model;

import java.util.Date;

public class OrderItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.id
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.lineNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String lineNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.sku
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.amount
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.unit
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orderId
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orderStatus
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.productName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.trackingNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String trackingNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.carrierName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String carrierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.methodCode
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private String methodCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.shipDate
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    private Date shipDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.id
     *
     * @return the value of orderitem.id
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.id
     *
     * @param id the value for orderitem.id
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.lineNumber
     *
     * @return the value of orderitem.lineNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getLineNumber() {
        return lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.lineNumber
     *
     * @param lineNumber the value for orderitem.lineNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setLineNumber(String lineNumber) {
        this.lineNumber = lineNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.sku
     *
     * @return the value of orderitem.sku
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.sku
     *
     * @param sku the value for orderitem.sku
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.amount
     *
     * @return the value of orderitem.amount
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.amount
     *
     * @param amount the value for orderitem.amount
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.unit
     *
     * @return the value of orderitem.unit
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.unit
     *
     * @param unit the value for orderitem.unit
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orderId
     *
     * @return the value of orderitem.orderId
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orderId
     *
     * @param orderId the value for orderitem.orderId
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orderStatus
     *
     * @return the value of orderitem.orderStatus
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orderStatus
     *
     * @param orderStatus the value for orderitem.orderStatus
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.productName
     *
     * @return the value of orderitem.productName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.productName
     *
     * @param productName the value for orderitem.productName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.trackingNumber
     *
     * @return the value of orderitem.trackingNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.trackingNumber
     *
     * @param trackingNumber the value for orderitem.trackingNumber
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.carrierName
     *
     * @return the value of orderitem.carrierName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.carrierName
     *
     * @param carrierName the value for orderitem.carrierName
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.methodCode
     *
     * @return the value of orderitem.methodCode
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public String getMethodCode() {
        return methodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.methodCode
     *
     * @param methodCode the value for orderitem.methodCode
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setMethodCode(String methodCode) {
        this.methodCode = methodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.shipDate
     *
     * @return the value of orderitem.shipDate
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public Date getShipDate() {
        return shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.shipDate
     *
     * @param shipDate the value for orderitem.shipDate
     *
     * @mbggenerated Tue Jul 11 14:38:01 CST 2017
     */
    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }
}