package com.erp.db.model;

import java.util.Date;

public class ShippingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.id
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.orderId
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private Integer orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.phone
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.name
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.address1
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.address2
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.city
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.state
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.postalCode
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.country
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.addressType
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private String addressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.estimatedDeliveryDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private Date estimatedDeliveryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shippinginfo.estimatedShipDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    private Date estimatedShipDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.id
     *
     * @return the value of shippinginfo.id
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.id
     *
     * @param id the value for shippinginfo.id
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.orderId
     *
     * @return the value of shippinginfo.orderId
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.orderId
     *
     * @param orderId the value for shippinginfo.orderId
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.phone
     *
     * @return the value of shippinginfo.phone
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.phone
     *
     * @param phone the value for shippinginfo.phone
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.name
     *
     * @return the value of shippinginfo.name
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.name
     *
     * @param name the value for shippinginfo.name
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.address1
     *
     * @return the value of shippinginfo.address1
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.address1
     *
     * @param address1 the value for shippinginfo.address1
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.address2
     *
     * @return the value of shippinginfo.address2
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.address2
     *
     * @param address2 the value for shippinginfo.address2
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.city
     *
     * @return the value of shippinginfo.city
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.city
     *
     * @param city the value for shippinginfo.city
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.state
     *
     * @return the value of shippinginfo.state
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.state
     *
     * @param state the value for shippinginfo.state
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.postalCode
     *
     * @return the value of shippinginfo.postalCode
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.postalCode
     *
     * @param postalCode the value for shippinginfo.postalCode
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.country
     *
     * @return the value of shippinginfo.country
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.country
     *
     * @param country the value for shippinginfo.country
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.addressType
     *
     * @return the value of shippinginfo.addressType
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public String getAddressType() {
        return addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.addressType
     *
     * @param addressType the value for shippinginfo.addressType
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setAddressType(String addressType) {
        this.addressType = addressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.estimatedDeliveryDate
     *
     * @return the value of shippinginfo.estimatedDeliveryDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public Date getEstimatedDeliveryDate() {
        return estimatedDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.estimatedDeliveryDate
     *
     * @param estimatedDeliveryDate the value for shippinginfo.estimatedDeliveryDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setEstimatedDeliveryDate(Date estimatedDeliveryDate) {
        this.estimatedDeliveryDate = estimatedDeliveryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shippinginfo.estimatedShipDate
     *
     * @return the value of shippinginfo.estimatedShipDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public Date getEstimatedShipDate() {
        return estimatedShipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shippinginfo.estimatedShipDate
     *
     * @param estimatedShipDate the value for shippinginfo.estimatedShipDate
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    public void setEstimatedShipDate(Date estimatedShipDate) {
        this.estimatedShipDate = estimatedShipDate;
    }
}