package com.erp.db.model;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.usertype
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.realname
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.consumerId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String consumerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.privateKey
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String privateKey;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.id
     *
     * @return the value of userinfo.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.id
     *
     * @param id the value for userinfo.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.usertype
     *
     * @return the value of userinfo.usertype
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.usertype
     *
     * @param usertype the value for userinfo.usertype
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.realname
     *
     * @return the value of userinfo.realname
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.realname
     *
     * @param realname the value for userinfo.realname
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.consumerId
     *
     * @return the value of userinfo.consumerId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getConsumerId() {
        return consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.consumerId
     *
     * @param consumerId the value for userinfo.consumerId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setConsumerId(String consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.privateKey
     *
     * @return the value of userinfo.privateKey
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.privateKey
     *
     * @param privateKey the value for userinfo.privateKey
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }
}