package com.erp.view.model;

import java.util.List;

public class ViewOrderItem
{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Integer id;
    
    private String price_currency;
    
    private String inv_amount_unit;
    
    // orders start
    private Long statusDate;
    private String lineNumber;
    
    private String status;
    private String trackingInfo;
    
    private List<ViewCharge> charges;
    private List<ViewRefund> refunds;
    
    private String purchaseOrderId;
    //orders end

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.userId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.mart
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String mart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.sku
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.wpid
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String wpid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.upc
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String upc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.gtin
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String gtin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.productName
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.productType
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String productType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.currency
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.price_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Double price_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.publishedStatus
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String publishedStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.unit
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.inv_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Double inv_amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.fulfillmentLagTime
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    private Integer fulfillmentLagTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.userId
     *
     * @return the value of item.userId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.userId
     *
     * @param userId the value for item.userId
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.mart
     *
     * @return the value of item.mart
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getMart() {
        return mart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.mart
     *
     * @param mart the value for item.mart
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setMart(String mart) {
        this.mart = mart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.sku
     *
     * @return the value of item.sku
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.sku
     *
     * @param sku the value for item.sku
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setSku(String sku) {
        this.sku = sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.wpid
     *
     * @return the value of item.wpid
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getWpid() {
        return wpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.wpid
     *
     * @param wpid the value for item.wpid
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setWpid(String wpid) {
        this.wpid = wpid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.upc
     *
     * @return the value of item.upc
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getUpc() {
        return upc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.upc
     *
     * @param upc the value for item.upc
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setUpc(String upc) {
        this.upc = upc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.gtin
     *
     * @return the value of item.gtin
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getGtin() {
        return gtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.gtin
     *
     * @param gtin the value for item.gtin
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setGtin(String gtin) {
        this.gtin = gtin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.productName
     *
     * @return the value of item.productName
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.productName
     *
     * @param productName the value for item.productName
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.productType
     *
     * @return the value of item.productType
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.productType
     *
     * @param productType the value for item.productType
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.currency
     *
     * @return the value of item.currency
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.currency
     *
     * @param currency the value for item.currency
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.price_amount
     *
     * @return the value of item.price_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Double getPrice_amount() {
        return price_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.price_amount
     *
     * @param price_amount the value for item.price_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setPrice_amount(Double price_amount) {
        this.price_amount = price_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.publishedStatus
     *
     * @return the value of item.publishedStatus
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getPublishedStatus() {
        return publishedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.publishedStatus
     *
     * @param publishedStatus the value for item.publishedStatus
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setPublishedStatus(String publishedStatus) {
        this.publishedStatus = publishedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.unit
     *
     * @return the value of item.unit
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.unit
     *
     * @param unit the value for item.unit
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.inv_amount
     *
     * @return the value of item.inv_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Double getInv_amount() {
        return inv_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.inv_amount
     *
     * @param inv_amount the value for item.inv_amount
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setInv_amount(Double inv_amount) {
        this.inv_amount = inv_amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.fulfillmentLagTime
     *
     * @return the value of item.fulfillmentLagTime
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public Integer getFulfillmentLagTime() {
        return fulfillmentLagTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.fulfillmentLagTime
     *
     * @param fulfillmentLagTime the value for item.fulfillmentLagTime
     *
     * @mbggenerated Wed May 31 17:22:58 CST 2017
     */
    public void setFulfillmentLagTime(Integer fulfillmentLagTime) {
        this.fulfillmentLagTime = fulfillmentLagTime;
    }

    public String getPrice_currency()
    {
        return price_currency;
    }

    public void setPrice_currency(String price_currency)
    {
        this.price_currency = price_currency;
    }

    public String getInv_amount_unit()
    {
        return inv_amount_unit;
    }

    public void setInv_amount_unit(String inv_amount_unit)
    {
        this.inv_amount_unit = inv_amount_unit;
    }

    public Long getStatusDate()
    {
        return statusDate;
    }

    public void setStatusDate(Long statusDate)
    {
        this.statusDate = statusDate;
    }

    public String getStatus()
    {
        return status;
    }

    public void setStatus(String status)
    {
        this.status = status;
    }

    public String getTrackingInfo()
    {
        return trackingInfo;
    }

    public void setTrackingInfo(String trackingInfo)
    {
        this.trackingInfo = trackingInfo;
    }

    public List<ViewCharge> getCharges()
    {
        return charges;
    }

    public void setCharges(List<ViewCharge> charges)
    {
        this.charges = charges;
    }

    public List<ViewRefund> getRefunds()
    {
        return refunds;
    }

    public void setRefunds(List<ViewRefund> refunds)
    {
        this.refunds = refunds;
    }

    public String getLineNumber()
    {
        return lineNumber;
    }

    public void setLineNumber(String lineNumber)
    {
        this.lineNumber = lineNumber;
    }

    public String getPurchaseOrderId()
    {
        return purchaseOrderId;
    }

    public void setPurchaseOrderId(String purchaseOrderId)
    {
        this.purchaseOrderId = purchaseOrderId;
    }
}
