package com.erp.db.mapper;

import com.erp.db.model.Charges;
import com.erp.db.model.ChargesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChargesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int countByExample(ChargesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int deleteByExample(ChargesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int insert(Charges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int insertSelective(Charges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    List<Charges> selectByExample(ChargesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    Charges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") Charges record, @Param("example") ChargesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int updateByExample(@Param("record") Charges record, @Param("example") ChargesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int updateByPrimaryKeySelective(Charges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charges
     *
     * @mbggenerated Tue Jul 11 11:08:57 CST 2017
     */
    int updateByPrimaryKey(Charges record);
}