package com.erp.db.mapper;

import com.erp.db.model.Feed;
import com.erp.db.model.FeedExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int countByExample(FeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int deleteByExample(FeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int insert(Feed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int insertSelective(Feed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    List<Feed> selectByExample(FeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    Feed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int updateByExampleSelective(@Param("record") Feed record, @Param("example") FeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int updateByExample(@Param("record") Feed record, @Param("example") FeedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int updateByPrimaryKeySelective(Feed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbggenerated Mon Jun 05 15:23:18 CST 2017
     */
    int updateByPrimaryKey(Feed record);
}