package com.erp.db.mapper;

import com.erp.db.model.ShippingInfo;
import com.erp.db.model.ShippingInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShippingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int countByExample(ShippingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int deleteByExample(ShippingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int insert(ShippingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int insertSelective(ShippingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    List<ShippingInfo> selectByExample(ShippingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    ShippingInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") ShippingInfo record, @Param("example") ShippingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int updateByExample(@Param("record") ShippingInfo record, @Param("example") ShippingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int updateByPrimaryKeySelective(ShippingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shippinginfo
     *
     * @mbggenerated Tue Jul 11 13:42:58 CST 2017
     */
    int updateByPrimaryKey(ShippingInfo record);
}